version: "3"
services:
  django:
    container_name: cifrador_django
    build:
      context: ./
      dockerfile: docker/DockerfileDjango
    command: 
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python manage.py runserver 0.0.0.0:8000
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/code

